import os

PYTHON_VERSION = os.getenv("PYTHON_VERSION", "3.12")
NODE_VERSION = os.getenv("NODE_VERSION", "24")
RUST_VERSION = os.getenv("RUST_VERSION", "1.94.1")
GO_VERSION = os.getenv("GO_VERSION", "1.26.1")
BUN_VERSION = os.getenv("BUN_VERSION", "1.3.11")

DEFAULT_SANDBOX_TIMEOUT = os.getenv("DEFAULT_SANDBOX_TIMEOUT", 3600)
DEFAULT_SANDBOX_IDLE_TIMEOUT = os.getenv("DEFAULT_SANDBOX_IDLE_TIMEOUT", 360)
DEFAULT_EXEC_TIMEOUT = int(os.getenv("DEFAULT_EXEC_TIMEOUT", 360))

DEFAULT_ENCRYPTED_PORTS = os.getenv("DEFAULT_ENCRYPTED_PORTS", "22,4222")
DEFAULT_UNENCRYPTED_PORTS = os.getenv(
    "DEFAULT_UNENCRYPTED_PORTS", "3000,5173,8000,8080"
)
DEFAULT_WORKDIR = os.getenv("DEFAULT_WORKDIR", "/code")
